include $(TOPDIR)/rules.mk

NAME:=poweroff
PKG_NAME:=luci-app-$(NAME)
LUCI_TITLE:=LuCI support for poweroffdevice Router
LUCI_DESCRIPTION:=provides Web UI to shut down (power off) your device. 

LUCI_PKGARCH:=all
PKG_VERSION:=1.0.0
PKG_RELEASE:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
