include $(TOPDIR)/rules.mk

NAME:=ynn-nas-client
PKG_NAME:=luci-app-$(NAME)
LUCI_TITLE:=LuCI support for ynn-nas-client
LUCI_DESCRIPTION:=ynn nas client
LUCI_DEPENDS:=+ynn-nas-client

LUCI_PKGARCH:=all
PKG_VERSION:=1.0.1
PKG_RELEASE:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
